# Generated by Django 5.2.7 on 2025-10-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_images_productbrand_image_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.file'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.file'),
        ),
    ]
