# Generated by Django 5.2.7 on 2025-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
            ('dashboard', '0002_remove_abandoned_at_fix_indexes'),
    ]

    operations = [
        migration.RenameIndex(
            model_name='cartabandonment',
            new_name='dashboard_c_product_a63ee3_idx',
            old_name='dashboard_c_product_created_idx',
        ),
        migration.RenameIndex(
            model_name='cartabandonment',
            new_name='dashboard_c_user_id_17a56b_idx',
            old_name='dashboard_c_user_created_idx',
        ),
    ]
