# Generated by Django 5.2.7 on 2025-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_billing_address_order_contact_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
