# Generated by Django 5.2.7 on 2025-11-28 15:33

import django.db.models.deletion
from django.db import migrations, models

def backfill_orderitem_fields(apps, schema_editor):
    OrderItem = apps.get_model('checkout', 'OrderItem')
    for item in OrderItem.objects.all():
        if item.cart_item:
            item.product = item.cart_item.product
            item.quantity = item.cart_item.quantity
            item.save()



class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_payment_stripe_session_id'),
        ('products', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        
        migrations.RunPython(backfill_orderitem_fields, reverse_code=migrations.RunPython.noop),
    ]


