// Export all API services from a single entry point
export { authService } from './auth/authService'
export { productService } from './products/productService'
export { cartService } from './cart/cartService'
export { orderService } from './orders/orderService'
export { userService } from './user/userService'
export { wishlistService } from './wishlist/wishlistService'
export { ticketService } from './support/ticketService'
export { notificationService } from './notifications/notificationService'
export { newsletterService } from './newsletter/newsletterService'
export { adminDashboardService } from './admin-dashboard/adminDashboardService'
export { productStatisticsService } from './product-statistics/productStatisticsService'
export { apiClient } from './client'
