# Generated by Django 5.2.7 on 2025-11-11 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Create a new UUID column
        migrations.AddField(
            model_name='contactmessage',
            name='id_new',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Remove the old primary key constraint and make id_new the primary key
        migrations.RemoveField(
            model_name='contactmessage',
            name='id',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='id_new',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
