# Generated by Django 5.2.7 on 2026-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_is_deleted_contactmessage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('resolved', 'Resolved')], default='unread', max_length=20),
        ),
    ]
